services:
  app:
    image: ghcr.io/adityadarma/tunnelcode:latest
    container_name: tunnelcode
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
    environment:
      - TZ=Asia/Makassar
    networks:
      - internet

networks:
  internet:
    external: true