import { z } from 'zod';
import { approvalNumberSchema, pairingCodeSchema, requestIdSchema } from './ids.js';

/**
 * Body the browser posts to claim a pairing code. The code arrives from the QR
 * URL, everything else is generated by the server.
 */
export const pairRequestSchema = z.object({
  code: pairingCodeSchema,
});

/**
 * Response to a pair request. Pairing is not complete at this point: the user
 * still has to approve in the terminal. The browser shows approvalNumber so the
 * user can check it against the terminal.
 */
export const pairPendingSchema = z.object({
  status: z.literal('pending'),
  requestId: requestIdSchema,
  approvalNumber: approvalNumberSchema,
});

export const pairResultSchema = z.object({
  status: z.enum(['approved', 'rejected', 'expired']),
});

export type PairRequest = z.infer<typeof pairRequestSchema>;
export type PairPending = z.infer<typeof pairPendingSchema>;
export type PairResult = z.infer<typeof pairResultSchema>;
